### ISSUE TITLE
Quoted references are deprecated in resource "provider" argument

### ISSUE THREAD

**Issue by eitah** [apparentlymart/terraform-clean-syntax#13]
Thanks for writing this! 
I applied successfully - thanks for this, it caught 8 instances of deprecated code. I was wondering, the warning I face now is only `Warning: Quoted references are deprecated`

Any procedural way to catch those that you recommend? I googled around a bit, but nothing looked promising.

**Comment by apparentlymart** [comment]
Can you include a full example of one or more or those warnings so I can see exactly what situation you're talking about? It's possible that this tool could be extended to cover some more things, as long as they are things that can be rewritten safely, but for the first pass here I focused on the most common cases.

**Comment by eitah** [comment]
https://github.com/eitah/tf-clean-syntax-issue here ya go. it makes a warning but it doesn't actually catch the quoted provider alias.

**Comment by apparentlymart** [comment]
Ahh, thanks... I see what you mean now.

This seems like something that `terraform-clean-syntax` could potentially handle, with a similar approach to how it handles `type` inside `variable` blocks:

https://github.com/apparentlymart/terraform-clean-syntax/blob/50d656f45b7f77dbee4a2f37bdca8dba96f444e0/main.go#L123-L127

In this case it would be `(inBlocks[0] == "resource" || inBlocks[0] == "data") && name == "provider"`, I suppose, and then it could use a similar function to `cleanTypeExpr`, in this case still checking if the expression is a quoted string but then if so just unwrapping the quotes from it without any further processing, because the quoted and unquoted forms of provider configuration addresses are the same, unlike for variable type constraints.

I don't personally have time to make additions to this tool right now because my focus is on other projects, but I'd love to review a pull request if someone had the time and motivation to work on it.
